blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/muhammad-fiaz/zig-dependabot/discussions
    about: Ask questions and discuss with the community
  - name: Security policy
    url: https://github.com/muhammad-fiaz/zig-dependabot/security/policy
    about: Read our security policy
